MYONGSIK.xcodeproj/project.pbxproj, MYONGSIK/Resource/Support/AppDelegate.swift, MYONGSIK/Resource/Support/RegisterUUID.swift, MYONGSIK/Source/Data/Network/APIManager.swift, MYONGSIK/Source/Domain/Entity/UserModel.swift
prExplanation
🔑 Key Changes
- 앱 최초 접속시 디바이스 넘버로 유저 등록 기능 추가
- 앱 첫 설치 및 버전 업데이트 모두 최초 접속으로 간주
=> feat: 앱 최초 접속시 디바이스 넘버로 유저 등록 기능 추가

MYONGSIK/Source/Presentation/Heart/ViewControllers/HeartViewController.swift
=> feat: 찜꽁리스트 베이스 뷰 변경

MYONGSIK.xcodeproj/project.pbxproj, MYONGSIK/Resource/UI/UIResponder+.swift, MYONGSIK/Source/Data/Network/Constants.swift, MYONGSIK/Source/Domain/Entity/DayFoodModel.swift, MYONGSIK/Source/Presentation/Main/Cells/MainTableViewCell.swift, MYONGSIK/Source/Presentation/Main/Cells/ThumbButtonSetPopupViewController.swift, MYONGSIK/Source/Presentation/Main/ViewControllers/MainViewController.swift
prExplanation
🔑 Key Changes
- 맛있어요/맛없어요 팝업뷰 추가
- 당일 학식 정보에 대해서만 평가 가능하도록 기능 추가
=> feat: 맛있어요/맛없어요 팝업뷰 추가 및 당일 학식 정보에 대해서만 평가 가능하도록 기능 추가

MYONGSIK/Resource/Support/SceneDelegate.swift, MYONGSIK/Source/Presentation/Main/ViewControllers/MainViewController.swift
prExplanation
🔑 Key Changes
- change1
- change2
📢 To Reviewers
toReviewers
=> Feat/home UI 레이아웃 수정

MYONGSIK/Source/Presentation/Launch/Splash/SplashViewController.swift, MYONGSIK/Source/Presentation/Main/ViewControllers/MainViewController.swift
🔑 Key Changes
- 노치 여부에 따른 스플래시 레이아웃 수정 
- 데이터 개수에 따른 pageControl과 의견 제출 버튼 hidden처리 수정
=> Feat/home UI

MYONGSIK/Source/Presentation/Main/ViewModels/SubmitViewController.swift
🔑 Key Changes
- 학식 의견 제출 서버 연동 구현
=> feat: 학식 의견 제출 서버 연동 구현

MYONGSIK/Source/Presentation/Main/ViewControllers/MainViewController.swift, MYONGSIK/Source/Presentation/Main/ViewModels/SubmitViewController.swift
mealId에 대한 임시 처리 반영
🔑 Key Changes
- 선택된 날짜의 0번째 학식에 대한 의견으로 제출하도록 수정
- 제출 뷰에 학식타입 선택에 대한 디자인이 추가되면 수정 예정
=> fix: 선택된 날짜의 0번째 학식에 대한 의견으로 제출하도록 수정

MYONGSIK/Source/Presentation/Main/ViewModels/SubmitViewController.swift
=> fix: 학식 의견 제출 request 모델 수정

MYONGSIK/Source/Presentation/Restaurant/Cells/SearchResultTableViewCell.swift, MYONGSIK/Source/Presentation/Restaurant/ViewControllers/RestaurantSearchViewController.swift
=> Feat/restaurant api : 찜꽁 기능 로컬구현으로 수정

MYONGSIK/Source/Presentation/Heart/Cells/HeartListTableViewCell.swift, MYONGSIK/Source/Presentation/Heart/ViewControllers/HeartViewController.swift
🔑 Key Changes
- 바로가기 버튼 제거
- 찜 버튼 추가
=> feat: 찜꽁리스트 셀 UI 변경

MYONGSIK/Source/Presentation/Restaurant/Cells/SearchResultTableViewCell.swift, MYONGSIK/Source/Presentation/Restaurant/ViewControllers/RestaurantMainViewController.swift, MYONGSIK/Source/Presentation/Restaurant/ViewControllers/RestaurantSearchViewController.swift
🔑 Key Changes
- 맛집 셀의 찜 버튼 제거
- 정렬 버튼 제거
=> Feat/restaurant UI

MYONGSIK/Source/Presentation/Heart/Cells/HeartListTableViewCell.swift, MYONGSIK/Source/Presentation/Heart/ViewControllers/HeartViewController.swift
🔑 Key Changes
- 마지막 1개의 찜을 취소할 경우 찜리스트가 비어있다는 라벨 표시 추가
- 찜꽁리스트 셀 레이아웃 수정
=> Feat/heart list UI

MYONGSIK/Source/Presentation/Launch/Splash/SplashViewController.swift, MYONGSIK/Source/Presentation/Main/ViewControllers/MainViewController.swift, MYONGSIK/Source/Presentation/Main/ViewControllers/SelectRestaurantViewController.swift, MYONGSIK/Source/Presentation/Utils/MainBaseViewController.swift
🔑 Key Changes
- 광고용 이미지뷰 제거
- 베이스 뷰 상단에 캠퍼스 전환 버튼 추가 (논의 후 사용 여부 결정)
=> feat: 광고용 이미지뷰 제거 및 베이스 뷰 상단에 캠퍼스 전환 버튼 추가

MYONGSIK/Source/Presentation/Launch/Splash/SplashViewController.swift, MYONGSIK/Source/Presentation/Main/Cells/MainTableViewCell.swift, MYONGSIK/Source/Presentation/Main/ViewControllers/MainViewController.swift, Podfile
🔑 Key Changes
- 홈 화면 데이터 패치 오류 처리
- 스플래시 팝업 추가
=> fix: 홈 화면 데이터 패치 오류 처리 및 스플래시 팝업 기능 추가

MYONGSIK/Info.plist, MYONGSIK/Resource/Support/SceneDelegate.swift, MYONGSIK/Source/Presentation/Main/ViewControllers/MainViewController.swift
🔑 Key Changes
- 자캠 홈 화면 레이아웃 관련 이슈
- 식당 선택 후 화면에서 back button 추가
- 라이트 모드 고정 값 추가 (info.plist)
=> feat: 자캠 홈 화면 레이아웃 관련 이슈 해결 및 식당 선택 후 화면에서 back button 추가

MYONGSIK.xcodeproj/project.pbxproj, MYONGSIK/GoogleService-Info.plist, MYONGSIK/Resource/Support/AppDelegate.swift
Firebase Analytics 추가
🔑 Key Changes
- Firebase Analytics 추가
📢 To Reviewers
이거 머지 후에 지도 잘되는지 테스트 부탁드리겠습니다~
=> [Chore] Firebase Analytics 추가

MYONGSIK/Resource/Support/AppDelegate.swift, MYONGSIK/Resource/Support/RegisterUUID.swift, Podfile
업데이트 혹은 삭제 후 재설치 마다 uuid 새롭게 들어가는 오류 수정
🔑 Key Changes
- uuid를 keychain에 저장
📢 To Reviewers
- keychain -> 아이폰 공장초기화 or 사용자가 keychain 삭제 하지 않는 이상 해당 정보 저장 및 불러오기 가능
=> [Fix] 업데이트 혹은 삭제 후 재설치 마다 uuid 새롭게 들어가는 오류 

DailyFoodWidget/DailyFoodWidget.swift, DailyFoodWidgetExtension.entitlements, MYONGSIK.xcodeproj/project.pbxproj, MYONGSIK/MYONGSIK.entitlements, MYONGSIK/Resource/Extensions/UserDefaults+.swift, MYONGSIK/Resource/Support/SceneDelegate.swift, MYONGSIK/Source/Presentation/Launch/Splash/CampusSetPopupViewController.swift, MYONGSIK/Source/Presentation/Main/Cells/SettingResTableViewCell.swift, MYONGSIK/Source/Presentation/Main/ViewControllers/MainViewController.swift, MYONGSIK/Source/Presentation/Main/ViewControllers/SettingRestautrantViewController.swift, MYONGSIK/Source/Presentation/Utils/MainBaseViewController.swift
위젯 설정 화면 구현 및 위젯에 데이터 연동
🔑 Key Changes
- 자연캠인 경우 위젯 설정 화면 추가
- 앱에서 저장된 식당 데이터를 위젯과 연동
📢 To Reviewers
toReviewers
=> [Feature] 위젯 설정 화면 및 위젯과 데이터 연동 구현

MYONGSIK/Resource/Support/AppDelegate.swift, MYONGSIK/Resource/Support/RegisterUUID.swift, MYONGSIK/Source/Presentation/Heart/Cells/HeartListTableViewCell.swift, MYONGSIK/Source/Presentation/Heart/ViewControllers/HeartViewController.swift, MYONGSIK/Source/Presentation/Main/ViewModels/SubmitViewController.swift, MYONGSIK/Source/Presentation/Map/ViewController/MapViewController.swift, MYONGSIK/Source/Presentation/Restaurant/ViewControllers/WebViewController.swift
찜하기 cell 선택 시 상세 뷰 UI 구현
🔑 Key Changes
- 찜하기 Cell 선택 시 상세 뷰 구현
📢 To Reviewers
toReviewers
=> [feature] 찜하기 cell 선택 시 상세 뷰 UI 구현

MYONGSIK/Resource/Support/AppDelegate.swift, MYONGSIK/Resource/Support/RegisterUUID.swift, MYONGSIK/Source/Presentation/Heart/Cells/HeartListTableViewCell.swift, MYONGSIK/Source/Presentation/Heart/ViewControllers/HeartViewController.swift, MYONGSIK/Source/Presentation/Main/ViewControllers/MainViewController.swift, MYONGSIK/Source/Presentation/Main/ViewModels/SubmitViewController.swift, MYONGSIK/Source/Presentation/Map/ViewController/MapViewController.swift, MYONGSIK/Source/Presentation/Restaurant/ViewControllers/WebViewController.swift
일요일 식단 업데이트 및 찜콩리스트 선택시 거리 표시
🔑 Key Changes
- 일요일 식단 업데이트
-  찜콩리스트 선택시 거리 표시(Hot Fix)
📢 To Reviewers
toReviewers
=> [Chore, Hot Fix] 일요일 식단 업데이트 및 찜콩리스트 선택시 거리 표시

MYONGSIK/Source/Presentation/Main/ViewControllers/SettingRestautrantViewController.swift
prExplanation
🔑 Key Changes
- change1
- change2
📢 To Reviewers
toReviewers
=> chore: 불필요한 메소드 삭제

MYONGSIK/Source/Presentation/Main/ViewControllers/SettingRestautrantViewController.swift
prExplanation
🔑 Key Changes
- change1
- change2
📢 To Reviewers
toReviewers
=> chore: 불필요한 변수 및 메소드 삭제

MYONGSIK/Source/Presentation/Restaurant/ViewControllers/RestaurantMainViewController.swift
prExplanation
🔑 Key Changes
- change1
- change2
📢 To Reviewers
toReviewers
=> [Fix] 추천순으로 저장되었을 경우, 처음에 결과값이 안 뜨는 오류 처리

MYONGSIK/Source/Presentation/Map/ViewController/MapStoreView.swift
지도 상세뷰 전화 버튼 화면 잘림 오류 수정
🔑 Key Changes
-  지도 상세뷰 전화 버튼 화면 잘림 오류 수정
📢 To Reviewers
toReviewers
=> [fix] 지도 상세뷰 전화 버튼 화면 잘림 오류 수정

DailyFoodWidget/DailyFoodWidget.swift, MYONGSIK/Source/Presentation/Main/Cells/SettingResTableViewCell.swift, MYONGSIK/Source/Presentation/Main/ViewControllers/SettingRestautrantViewController.swift, MYONGSIK/Source/Presentation/Restaurant/ViewControllers/RestaurantMainViewController.swift
prExplanation
🔑 Key Changes
- 명지맛집 정렬 관련 셀 안 보임 이슈 처리
- 위젯 설정 화면 저장된 식당값 및 기본 식당값 표시
📢 To Reviewers
toReviewers
=> [Fix] 명지맛집 정렬 오류 처리 및 위젯 수정

DailyFoodWidget/DailyFoodWidget.swift
prExplanation
🔑 Key Changes
- change1
- change2
📢 To Reviewers
toReviewers
=> hot fix: 학관식당 조식/중식 라벨 변경

MYONGSIK/Source/Presentation/Main/ViewControllers/MainViewController.swift
prExplanation
🔑 Key Changes
- change1
- change2
📢 To Reviewers
toReviewers
=> hot fix: 인캠 학식메뉴 back button hidden 처리

MYONGSIK/Source/Presentation/Main/ViewControllers/MainViewController.swift, MYONGSIK/Source/Presentation/Map/ViewController/MapStoreView.swift
heart 중복되는 오류 수정
🔑 Key Changes
- heart 중복되는 오류 수정
📢 To Reviewers
toReviewers
=> [fix] heart 중복되는 오류 수정

DailyFoodWidget/DailyFoodWidget.swift
prExplanation
🔑 Key Changes
- change1
- change2
📢 To Reviewers
toReviewers
=> fix: 캠퍼스 미설정된 경우에 기본 값 MCC로 설정

MYONGSIK.xcodeproj/project.pbxproj, MYONGSIK/Info.plist, MYONGSIK/Resource/Support/AppDelegate.swift, MYONGSIK/Resource/Support/GoogleMobileAdsController.swift, MYONGSIK/Resource/Support/GoogleMobileAdsKey.swift, MYONGSIK/Source/Presentation/Main/ViewControllers/GaAdViewController.swift, MYONGSIK/Source/Presentation/Main/ViewControllers/MainViewController.swift, MYONGSIK/Source/Presentation/Main/ViewControllers/UpdateBottomAlertViewController.swift, Podfile
구글 광고 추가
🔑 Key Changes
- 구글 광고 sdk 추가
📢 To Reviewers
pod install 받기
GoogleMobileAdsKey에 있는 key는 테스트용 key입니다
=> [Feature] 구글 광고 추가

MYONGSIK/Source/Presentation/Main/ViewControllers/MainViewController.swift
=> [Fix] titleView 날짜 이동 버튼 event 재정의

MYONGSIK/Source/Presentation/Main/ViewControllers/MainViewController.swift
=> [Fix] 스와이프 시 날짜 변경 이슈 처리

MYONGSIK/Source/Presentation/Main/ViewControllers/MainViewController.swift
prExplanation
🔑 Key Changes
- change1
- change2
📢 To Reviewers
toReviewers
=> [Fix] 스와이프, 날짜 이동 버튼간 이벤트 결과 이슈 처리

MYONGSIK.xcodeproj/project.pbxproj, MYONGSIK/Source/Presentation/Restaurant/Cells/TagTableViewCell.swift
버전 업데이트 및 집밥 -> 맛집 수정
🔑 Key Changes
- 1.1.11 버전 업데이트
-  집밥 -> 맛집 수정
📢 To Reviewers
toReviewers
=> [Fix] 버전 업데이트 및 집밥 -> 맛집 수정

MYONGSIK/Source/Presentation/Main/ViewControllers/MainViewController.swift
=> [Fix] 일요일인 경우 차주 식단 조회 가능하도록 수정

MYONGSIK/Resource/Support/RegisterUUID.swift, MYONGSIK/Source/Presentation/Heart/ViewControllers/HeartViewController.swift, MYONGSIK/Source/Presentation/Map/ViewController/MapViewController.swift
찜콩리스트 안뜨는 오류 수정
🔑 Key Changes
-  찜콩리스트 안뜨는 오류 수정
📢 To Reviewers
toReviewers
=> [fix] 찜콩리스트 안뜨는 오류 수정

MYONGSIK.xcodeproj/project.pbxproj, MYONGSIK/Resource/Support/RegisterUUID.swift, MYONGSIK/Source/Presentation/Heart/ViewControllers/HeartViewController.swift, MYONGSIK/Source/Presentation/Main/ViewControllers/MainViewController.swift, MYONGSIK/Source/Presentation/Main/ViewControllers/SelectRestaurantViewController.swift, MYONGSIK/Source/Presentation/Main/ViewControllers/UpdateBottomAlertViewController.swift, MYONGSIK/Source/Presentation/Map/ViewController/MapViewController.swift, MYONGSIK/Source/Presentation/Restaurant/Cells/TagTableViewCell.swift, MYONGSIK/Source/Presentation/Restaurant/ViewControllers/WebViewController.swift, MYONGSIK/Source/Presentation/Utils/TabBarViewController.swift
1.1.14 메인 업데이트
🔑 Key Changes
- 1.1.14 메인 업데이트
📢 To Reviewers
toReviewers
=> [Update] 1.1.14 메인 업데이트

MYONGSIK/Source/Presentation/Web/ViewController/WebViewController.swift, MYONGSIK/Source/Presentation/Web/WebViewModel.swift
명지 맛집 바로가기 및 찜콩하기 ViewModel Input & Output 적용
🔑 Key Changes
- WebViewController 분리
- Web ViewModel 분리
📢 To Reviewers
toReviewers
=> refactor: 명지 맛집 바로가기 및 찜콩하기 ViewModel Input & Output 적용
